--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DICT_JC_TYPE
--------------------------------------------------------

  CREATE TABLE "TEST"."DICT_JC_TYPE" 
   (	"ID" NUMBER, 
	"JC_TYPE" VARCHAR2(255 BYTE), 
	"JC_TYPE_VALUE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."DICT_JC_TYPE"."ID" IS '主键<序列自增>';
 
   COMMENT ON COLUMN "TEST"."DICT_JC_TYPE"."JC_TYPE" IS '机车类型';
 
   COMMENT ON COLUMN "TEST"."DICT_JC_TYPE"."JC_TYPE_VALUE" IS '机车型号值';
 
   COMMENT ON TABLE "TEST"."DICT_JC_TYPE"  IS '机车型号表';
REM INSERTING into TEST.DICT_JC_TYPE
SET DEFINE OFF;
Insert into TEST.DICT_JC_TYPE (ID,JC_TYPE,JC_TYPE_VALUE) values (1,'DF4D','DF2562');
Insert into TEST.DICT_JC_TYPE (ID,JC_TYPE,JC_TYPE_VALUE) values (2,'DF5C','DF5656');
Insert into TEST.DICT_JC_TYPE (ID,JC_TYPE,JC_TYPE_VALUE) values (3,'HXD1','HX8954');
--------------------------------------------------------
--  DDL for Index SYS_C0012211
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012211" ON "TEST"."DICT_JC_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DICT_JC_TYPE
--------------------------------------------------------

  ALTER TABLE "TEST"."DICT_JC_TYPE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

