--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DICT_DEPART
--------------------------------------------------------

  CREATE TABLE "TEST"."DICT_DEPART" 
   (	"ID" NUMBER, 
	"DEPART_NAME" VARCHAR2(255 BYTE), 
	"PY" VARCHAR2(255 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."DICT_DEPART"."ID" IS '主键';
 
   COMMENT ON COLUMN "TEST"."DICT_DEPART"."DEPART_NAME" IS '角色名称';
 
   COMMENT ON COLUMN "TEST"."DICT_DEPART"."PY" IS '拼音';
 
   COMMENT ON COLUMN "TEST"."DICT_DEPART"."REMARK" IS '备注';
 
   COMMENT ON TABLE "TEST"."DICT_DEPART"  IS '部门表';
REM INSERTING into TEST.DICT_DEPART
SET DEFINE OFF;
Insert into TEST.DICT_DEPART (ID,DEPART_NAME,PY,REMARK) values (39,'集团领导','jdld','最高权力');
Insert into TEST.DICT_DEPART (ID,DEPART_NAME,PY,REMARK) values (36,'整备车间','zbcj','sdf');
Insert into TEST.DICT_DEPART (ID,DEPART_NAME,PY,REMARK) values (37,'约会去吧','yhqb','适当放宽就撒了');
Insert into TEST.DICT_DEPART (ID,DEPART_NAME,PY,REMARK) values (38,'测试部门',null,null);
--------------------------------------------------------
--  DDL for Index SYS_C0012185
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012185" ON "TEST"."DICT_DEPART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DICT_DEPART
--------------------------------------------------------

  ALTER TABLE "TEST"."DICT_DEPART" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

