--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DICT_PROTEAM
--------------------------------------------------------

  CREATE TABLE "TEST"."DICT_PROTEAM" 
   (	"ID" NUMBER, 
	"PROTEAM_NAME" VARCHAR2(255 BYTE), 
	"WORK_FLAG" NUMBER, 
	"ATTENDANCE_FLAG" NUMBER, 
	"VERSIONID" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."DICT_PROTEAM"."ID" IS '主键';
 
   COMMENT ON COLUMN "TEST"."DICT_PROTEAM"."PROTEAM_NAME" IS '班组名称';
 
   COMMENT ON COLUMN "TEST"."DICT_PROTEAM"."WORK_FLAG" IS '小辅修、中修判别字段：0、不修；1、小辅修；2、中修；3、小辅修/中修';
 
   COMMENT ON COLUMN "TEST"."DICT_PROTEAM"."ATTENDANCE_FLAG" IS '考勤判别字段：0、不考勤；1、考勤';
 
   COMMENT ON COLUMN "TEST"."DICT_PROTEAM"."VERSIONID" IS '乐观锁标识字段';
 
   COMMENT ON TABLE "TEST"."DICT_PROTEAM"  IS '班组表';
REM INSERTING into TEST.DICT_PROTEAM
SET DEFINE OFF;
Insert into TEST.DICT_PROTEAM (ID,PROTEAM_NAME,WORK_FLAG,ATTENDANCE_FLAG,VERSIONID) values (37,'静态配件测试班组',1,0,1);
Insert into TEST.DICT_PROTEAM (ID,PROTEAM_NAME,WORK_FLAG,ATTENDANCE_FLAG,VERSIONID) values (35,'制动组',1,0,33);
Insert into TEST.DICT_PROTEAM (ID,PROTEAM_NAME,WORK_FLAG,ATTENDANCE_FLAG,VERSIONID) values (36,'测试班组',1,0,1);
Insert into TEST.DICT_PROTEAM (ID,PROTEAM_NAME,WORK_FLAG,ATTENDANCE_FLAG,VERSIONID) values (40,'探伤组',1,0,0);
Insert into TEST.DICT_PROTEAM (ID,PROTEAM_NAME,WORK_FLAG,ATTENDANCE_FLAG,VERSIONID) values (39,'电器班组',1,0,0);
Insert into TEST.DICT_PROTEAM (ID,PROTEAM_NAME,WORK_FLAG,ATTENDANCE_FLAG,VERSIONID) values (38,'走行班组',1,0,0);
--------------------------------------------------------
--  DDL for Index SYS_C0012203
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012203" ON "TEST"."DICT_PROTEAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DICT_PROTEAM
--------------------------------------------------------

  ALTER TABLE "TEST"."DICT_PROTEAM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

