--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DICT_AREA
--------------------------------------------------------

  CREATE TABLE "TEST"."DICT_AREA" 
   (	"ID" VARCHAR2(255 BYTE), 
	"AREA_NAME" VARCHAR2(255 BYTE), 
	"JWD_CODE" VARCHAR2(255 BYTE), 
	"PY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."DICT_AREA"."ID" IS '主键';
 
   COMMENT ON COLUMN "TEST"."DICT_AREA"."AREA_NAME" IS '地区名称';
 
   COMMENT ON COLUMN "TEST"."DICT_AREA"."JWD_CODE" IS '机务段编号';
 
   COMMENT ON COLUMN "TEST"."DICT_AREA"."PY" IS '拼音';
 
   COMMENT ON TABLE "TEST"."DICT_AREA"  IS '班组表';
REM INSERTING into TEST.DICT_AREA
SET DEFINE OFF;
Insert into TEST.DICT_AREA (ID,AREA_NAME,JWD_CODE,PY) values ('2018','株洲机务段','0806','zzjwd');
Insert into TEST.DICT_AREA (ID,AREA_NAME,JWD_CODE,PY) values ('2019','长沙机务段','0804','csjwd');
Insert into TEST.DICT_AREA (ID,AREA_NAME,JWD_CODE,PY) values ('2016','龙川机务段','0803','lcjwd');
Insert into TEST.DICT_AREA (ID,AREA_NAME,JWD_CODE,PY) values ('2017','怀化机务段','0807','hhjwd');
Insert into TEST.DICT_AREA (ID,AREA_NAME,JWD_CODE,PY) values ('20144','衡阳机务段','0805','hyjwd');
--------------------------------------------------------
--  DDL for Index SYS_C0012199
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012199" ON "TEST"."DICT_AREA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DICT_AREA
--------------------------------------------------------

  ALTER TABLE "TEST"."DICT_AREA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

