--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DICT_STORE_POSITION
--------------------------------------------------------

  CREATE TABLE "TEST"."DICT_STORE_POSITION" 
   (	"ID" NUMBER, 
	"STORE_POSITION_NAME" VARCHAR2(255 BYTE), 
	"AREAID" VARCHAR2(255 BYTE), 
	"STORE_POSITION_TYPE" NUMBER, 
	"PY" VARCHAR2(255 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE), 
	"DICT_PROTEAM_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."DICT_STORE_POSITION"."ID" IS '主键';
 
   COMMENT ON COLUMN "TEST"."DICT_STORE_POSITION"."STORE_POSITION_NAME" IS '位置/仓库名';
 
   COMMENT ON COLUMN "TEST"."DICT_STORE_POSITION"."AREAID" IS '地区/机务段ID';
 
   COMMENT ON TABLE "TEST"."DICT_STORE_POSITION"  IS '配件所在位置/仓库表';
REM INSERTING into TEST.DICT_STORE_POSITION
SET DEFINE OFF;
Insert into TEST.DICT_STORE_POSITION (ID,STORE_POSITION_NAME,AREAID,STORE_POSITION_TYPE,PY,REMARK,DICT_PROTEAM_ID) values (25,'长沙机务段仓库','2019',0,null,null,35);
Insert into TEST.DICT_STORE_POSITION (ID,STORE_POSITION_NAME,AREAID,STORE_POSITION_TYPE,PY,REMARK,DICT_PROTEAM_ID) values (29,'衡阳机务段仓库','20144',2,null,null,36);
Insert into TEST.DICT_STORE_POSITION (ID,STORE_POSITION_NAME,AREAID,STORE_POSITION_TYPE,PY,REMARK,DICT_PROTEAM_ID) values (31,'株洲机务段仓库','2018',1,'cctt','fewfwe',37);
Insert into TEST.DICT_STORE_POSITION (ID,STORE_POSITION_NAME,AREAID,STORE_POSITION_TYPE,PY,REMARK,DICT_PROTEAM_ID) values (33,'龙川机务段仓库','2016',2,null,null,38);
Insert into TEST.DICT_STORE_POSITION (ID,STORE_POSITION_NAME,AREAID,STORE_POSITION_TYPE,PY,REMARK,DICT_PROTEAM_ID) values (32,'怀化机务段仓库','2017',1,'cctt','fewfwe',39);
--------------------------------------------------------
--  DDL for Index SYS_C0012206
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012206" ON "TEST"."DICT_STORE_POSITION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DICT_STORE_POSITION
--------------------------------------------------------

  ALTER TABLE "TEST"."DICT_STORE_POSITION" ADD CONSTRAINT "DSP_CK_TYPE" CHECK (STORE_POSITION_TYPE in(0,1,2,3)) ENABLE;
 
  ALTER TABLE "TEST"."DICT_STORE_POSITION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DICT_STORE_POSITION
--------------------------------------------------------

  ALTER TABLE "TEST"."DICT_STORE_POSITION" ADD CONSTRAINT "DSPDA_FOR" FOREIGN KEY ("AREAID")
	  REFERENCES "TEST"."DICT_AREA" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."DICT_STORE_POSITION" ADD CONSTRAINT "DSPDP_FOR" FOREIGN KEY ("DICT_PROTEAM_ID")
	  REFERENCES "TEST"."DICT_PROTEAM" ("ID") ENABLE;
