--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DICT_PJ_FIRST_UNIT
--------------------------------------------------------

  CREATE TABLE "TEST"."DICT_PJ_FIRST_UNIT" 
   (	"ID" NUMBER, 
	"FIRST_UNIT_NAME" VARCHAR2(255 BYTE), 
	"PY" VARCHAR2(255 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."DICT_PJ_FIRST_UNIT"."ID" IS '主键<序列增长>';
 
   COMMENT ON COLUMN "TEST"."DICT_PJ_FIRST_UNIT"."FIRST_UNIT_NAME" IS '大部件(专业)表';
 
   COMMENT ON COLUMN "TEST"."DICT_PJ_FIRST_UNIT"."PY" IS '拼音';
 
   COMMENT ON COLUMN "TEST"."DICT_PJ_FIRST_UNIT"."REMARK" IS '备注';
 
   COMMENT ON TABLE "TEST"."DICT_PJ_FIRST_UNIT"  IS '大部件(专业)表';
REM INSERTING into TEST.DICT_PJ_FIRST_UNIT
SET DEFINE OFF;
Insert into TEST.DICT_PJ_FIRST_UNIT (ID,FIRST_UNIT_NAME,PY,REMARK) values (21,'大部件测试','cs','haah ');
Insert into TEST.DICT_PJ_FIRST_UNIT (ID,FIRST_UNIT_NAME,PY,REMARK) values (6,'部件测试数据','bjcssj','我是部件测试数据');
Insert into TEST.DICT_PJ_FIRST_UNIT (ID,FIRST_UNIT_NAME,PY,REMARK) values (5,'电机','dj',null);
--------------------------------------------------------
--  DDL for Index SYS_C0012181
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012181" ON "TEST"."DICT_PJ_FIRST_UNIT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DICT_PJ_FIRST_UNIT
--------------------------------------------------------

  ALTER TABLE "TEST"."DICT_PJ_FIRST_UNIT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

