--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JC_MAIN_PLAN_RECORDER
--------------------------------------------------------

  CREATE TABLE "TEST"."JC_MAIN_PLAN_RECORDER" 
   (	"ID" NUMBER, 
	"JC_MAIN_PLAN_ID" NUMBER, 
	"JC_PLAN_DATE_ID" NUMBER, 
	"PLAN_DATE" VARCHAR2(255 BYTE), 
	"PLAN_WEEK" VARCHAR2(255 BYTE), 
	"MAIN_PLAN_NUM" NUMBER, 
	"JC_TYPE" VARCHAR2(255 BYTE), 
	"JC_TYPE_VALUE" VARCHAR2(255 BYTE), 
	"JC_NUMBER" VARCHAR2(255 BYTE), 
	"JC_FIX_MILEAGE_ID" NUMBER, 
	"PLAN_KILOMETRE" NUMBER, 
	"REALITY_KILOMETRE" NUMBER, 
	"AREA_ID" VARCHAR2(255 BYTE), 
	"CASH" NUMBER, 
	"NO_CASH_REASON" VARCHAR2(1000 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TEST.JC_MAIN_PLAN_RECORDER
SET DEFINE OFF;
Insert into TEST.JC_MAIN_PLAN_RECORDER (ID,JC_MAIN_PLAN_ID,JC_PLAN_DATE_ID,PLAN_DATE,PLAN_WEEK,MAIN_PLAN_NUM,JC_TYPE,JC_TYPE_VALUE,JC_NUMBER,JC_FIX_MILEAGE_ID,PLAN_KILOMETRE,REALITY_KILOMETRE,AREA_ID,CASH,NO_CASH_REASON,REMARK) values (34,16,null,'2015-11-16','星期一',1,'3','3','3',null,null,null,null,0,null,null);
Insert into TEST.JC_MAIN_PLAN_RECORDER (ID,JC_MAIN_PLAN_ID,JC_PLAN_DATE_ID,PLAN_DATE,PLAN_WEEK,MAIN_PLAN_NUM,JC_TYPE,JC_TYPE_VALUE,JC_NUMBER,JC_FIX_MILEAGE_ID,PLAN_KILOMETRE,REALITY_KILOMETRE,AREA_ID,CASH,NO_CASH_REASON,REMARK) values (35,16,null,'2015-11-17','星期二',2,'2','2','2',null,null,null,null,0,null,null);
Insert into TEST.JC_MAIN_PLAN_RECORDER (ID,JC_MAIN_PLAN_ID,JC_PLAN_DATE_ID,PLAN_DATE,PLAN_WEEK,MAIN_PLAN_NUM,JC_TYPE,JC_TYPE_VALUE,JC_NUMBER,JC_FIX_MILEAGE_ID,PLAN_KILOMETRE,REALITY_KILOMETRE,AREA_ID,CASH,NO_CASH_REASON,REMARK) values (36,16,null,'2015-11-18','星期三',3,'1','1','1',null,null,null,null,0,null,null);
Insert into TEST.JC_MAIN_PLAN_RECORDER (ID,JC_MAIN_PLAN_ID,JC_PLAN_DATE_ID,PLAN_DATE,PLAN_WEEK,MAIN_PLAN_NUM,JC_TYPE,JC_TYPE_VALUE,JC_NUMBER,JC_FIX_MILEAGE_ID,PLAN_KILOMETRE,REALITY_KILOMETRE,AREA_ID,CASH,NO_CASH_REASON,REMARK) values (20,12,null,null,null,1,'机型','机型','1234',null,2,2,null,0,null,'22222');
--------------------------------------------------------
--  DDL for Index SYS_C0012207
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012207" ON "TEST"."JC_MAIN_PLAN_RECORDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JC_MAIN_PLAN_RECORDER
--------------------------------------------------------

  ALTER TABLE "TEST"."JC_MAIN_PLAN_RECORDER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JC_MAIN_PLAN_RECORDER
--------------------------------------------------------

  ALTER TABLE "TEST"."JC_MAIN_PLAN_RECORDER" ADD FOREIGN KEY ("JC_MAIN_PLAN_ID")
	  REFERENCES "TEST"."JC_MAIN_PLAN" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_MAIN_PLAN_RECORDER" ADD FOREIGN KEY ("JC_PLAN_DATE_ID")
	  REFERENCES "TEST"."JC_PLAN_DATE" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_MAIN_PLAN_RECORDER" ADD FOREIGN KEY ("JC_FIX_MILEAGE_ID")
	  REFERENCES "TEST"."DICT_JC_FIX_MILEAGE" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_MAIN_PLAN_RECORDER" ADD FOREIGN KEY ("AREA_ID")
	  REFERENCES "TEST"."DICT_AREA" ("ID") ENABLE;
