--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JC_PLAN_DATE
--------------------------------------------------------

  CREATE TABLE "TEST"."JC_PLAN_DATE" 
   (	"ID" NUMBER, 
	"JC_TYPE" VARCHAR2(255 BYTE), 
	"JC_TYPE_VALUE" VARCHAR2(255 BYTE), 
	"JC_NUMBER" NUMBER, 
	"JC_FIX_MILEAGE_ID" NUMBER, 
	"JC_DETAIN_TIEM" TIMESTAMP (6), 
	"JC_PLAN_START_TIME" TIMESTAMP (6), 
	"JC_PLAN_RECEIVE_TIME" TIMESTAMP (6), 
	"QC_USERS_ID" NUMBER, 
	"COMMIT_LEAD_USERS_ID" NUMBER, 
	"JC_PLAN_STATUS" NUMBER, 
	"STATION_RACKS_NUMBER" VARCHAR2(255 BYTE), 
	"STATION_NUMBER" VARCHAR2(255 BYTE), 
	"PLAN_MAKER" VARCHAR2(255 BYTE), 
	"PLAN_MAKE_TIME" TIMESTAMP (6), 
	"FIX_FLOW_ID" NUMBER, 
	"ACCEPTANCE_USERS_ID" NUMBER, 
	"TECHNICIAN_USERS_ID" NUMBER, 
	"PROJECT_TYPE" NUMBER, 
	"ACTUAL_STAR_TTIME" TIMESTAMP (6), 
	"ACTUAL_RECEIVE_TIME" TIMESTAMP (6), 
	"NO_PROTEAM_IDS" VARCHAR2(1000 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into TEST.JC_PLAN_DATE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C0012188
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012188" ON "TEST"."JC_PLAN_DATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table JC_PLAN_DATE
--------------------------------------------------------

  ALTER TABLE "TEST"."JC_PLAN_DATE" MODIFY ("JC_FIX_MILEAGE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."JC_PLAN_DATE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JC_PLAN_DATE
--------------------------------------------------------

  ALTER TABLE "TEST"."JC_PLAN_DATE" ADD FOREIGN KEY ("JC_FIX_MILEAGE_ID")
	  REFERENCES "TEST"."DICT_JC_FIX_MILEAGE" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_PLAN_DATE" ADD FOREIGN KEY ("QC_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_PLAN_DATE" ADD FOREIGN KEY ("COMMIT_LEAD_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_PLAN_DATE" ADD FOREIGN KEY ("FIX_FLOW_ID")
	  REFERENCES "TEST"."JC_FIX_FLOW" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_PLAN_DATE" ADD FOREIGN KEY ("ACCEPTANCE_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."JC_PLAN_DATE" ADD FOREIGN KEY ("TECHNICIAN_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
