--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_FIX_ITEM
--------------------------------------------------------

  CREATE TABLE "TEST"."PJ_FIX_ITEM" 
   (	"ID" NUMBER, 
	"PARENT_ID" NUMBER, 
	"FIX_ITEM_NAME" VARCHAR2(255 BYTE), 
	"FIX_ITEM_PART" VARCHAR2(255 BYTE), 
	"PJ_STATIC_ID" NUMBER, 
	"FIX_ITEM_NUMBER" NUMBER, 
	"DEFAULT_VALUE" VARCHAR2(255 BYTE), 
	"SHOW_STATUS" NUMBER, 
	"PROTEAM_ID" NUMBER, 
	"LEAD_CHECK" NUMBER, 
	"COMMIT_LEAD_CHECK" NUMBER, 
	"QC_CHECK" NUMBER, 
	"ACCEPTANCE_CHECK" NUMBER, 
	"TECHNICIAN_CHECK" NUMBER, 
	"TWO_INSPECTION_CHECK" NUMBER, 
	"MIN_VALUE" NUMBER, 
	"MAX_VALUE" NUMBER, 
	"UNIT_MEASURE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."ID" IS '主键<序列自增>';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."PARENT_ID" IS '父ID，有父ID的项目为子项目';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."FIX_ITEM_NAME" IS '配件检修项目名称';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."FIX_ITEM_PART" IS '配件检修项目-部位名称';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."PJ_STATIC_ID" IS '配件静态信息ID';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."FIX_ITEM_NUMBER" IS '配件检修项目顺序号';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."DEFAULT_VALUE" IS '项目填报默认值';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."SHOW_STATUS" IS '项目在查询报表显示状态：0、不显示；1显示';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."PROTEAM_ID" IS '项目检修班组ID';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."LEAD_CHECK" IS '工长是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."COMMIT_LEAD_CHECK" IS '交车工长是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."QC_CHECK" IS '质检员是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."ACCEPTANCE_CHECK" IS '验收员是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."TECHNICIAN_CHECK" IS '技术员是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."TWO_INSPECTION_CHECK" IS '复探是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."MIN_VALUE" IS '最小值（double,10）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."MAX_VALUE" IS '最大值（double,10）';
 
   COMMENT ON COLUMN "TEST"."PJ_FIX_ITEM"."UNIT_MEASURE" IS '计量单位';
 
   COMMENT ON TABLE "TEST"."PJ_FIX_ITEM"  IS '配件检修项目表';
REM INSERTING into TEST.PJ_FIX_ITEM
SET DEFINE OFF;
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (9,null,'测试检测项目9','右端',21,1,null,1,36,1,1,1,1,1,1,null,null,'mm');
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (1,null,'测试检修项目1','左端',21,1,null,1,36,1,1,1,1,1,1,null,null,null);
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (2,null,'测试检修项目2','左端',21,1,null,1,36,1,1,1,1,1,1,null,null,null);
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (3,null,'测试检修项目3','左端',21,1,'2',1,36,1,1,1,1,1,1,null,null,null);
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (4,null,'测试检修项目4','左端',21,1,'5',1,36,1,1,1,1,1,1,null,null,null);
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (5,null,'测试检修项目5','左端',22,1,null,1,36,1,1,1,1,1,1,null,null,null);
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (6,null,'测试检修项目6','左端',22,1,null,1,36,1,1,1,1,1,1,null,null,null);
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (7,null,'测试检修项目7','左端',22,1,null,1,36,1,1,1,1,1,1,null,null,null);
Insert into TEST.PJ_FIX_ITEM (ID,PARENT_ID,FIX_ITEM_NAME,FIX_ITEM_PART,PJ_STATIC_ID,FIX_ITEM_NUMBER,DEFAULT_VALUE,SHOW_STATUS,PROTEAM_ID,LEAD_CHECK,COMMIT_LEAD_CHECK,QC_CHECK,ACCEPTANCE_CHECK,TECHNICIAN_CHECK,TWO_INSPECTION_CHECK,MIN_VALUE,MAX_VALUE,UNIT_MEASURE) values (8,null,'测试检修项目8','左端',21,1,null,1,36,1,1,1,1,1,1,null,null,null);
--------------------------------------------------------
--  DDL for Index SYS_C0012221
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012221" ON "TEST"."PJ_FIX_ITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PJ_FIX_ITEM
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFI_CK_A_CHECK" CHECK (ACCEPTANCE_CHECK in(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFI_CK_C_L_CHECK" CHECK (COMMIT_LEAD_CHECK in(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFI_CK_L_CHECK" CHECK (LEAD_CHECK in(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFI_CK_Q_CHECK" CHECK (QC_CHECK in(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFI_CK_STATUS" CHECK (SHOW_STATUS in(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFI_CK_T_CHECK" CHECK (TECHNICIAN_CHECK in(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFI_CK_T_M_CHECK" CHECK ("TWO_INSPECTION_CHECK"=0 OR "TWO_INSPECTION_CHECK"=1) ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_FIX_ITEM
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFIDP_FOR" FOREIGN KEY ("PROTEAM_ID")
	  REFERENCES "TEST"."DICT_PROTEAM" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFIPFI_FOR" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "TEST"."PJ_FIX_ITEM" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_FIX_ITEM" ADD CONSTRAINT "PFIPSSI_FOR" FOREIGN KEY ("PJ_STATIC_ID")
	  REFERENCES "TEST"."PJ_STORE_STATIC_INFO" ("ID") ENABLE;
