--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_S_D_INFO_RECORD
--------------------------------------------------------

  CREATE TABLE "TEST"."PJ_S_D_INFO_RECORD" 
   (	"ID" NUMBER, 
	"RECEIVING_DELIVER_STATUS" NUMBER, 
	"STORE_UNIT_PROTEAM_STATUS" NUMBER, 
	"PJ_STORE_DYNAMIC_INFO_ID" NUMBER, 
	"RECORD_TIEM" TIMESTAMP (6), 
	"REMARK" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD"."ID" IS '主键<序列自增>';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD"."RECEIVING_DELIVER_STATUS" IS '是入库，还是出库（移库）:0、入库；1，出库（移库）';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD"."STORE_UNIT_PROTEAM_STATUS" IS '0、主仓库-班组仓库，出库入库；1、班组仓库-班组仓库，出库入库；2、主仓库-相关单位，出库入库';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD"."PJ_STORE_DYNAMIC_INFO_ID" IS '配件仓库动态信息/库存(所在位置)表ID-配件动态ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD"."RECORD_TIEM" IS '记录时间';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD"."REMARK" IS '备注';
REM INSERTING into TEST.PJ_S_D_INFO_RECORD
SET DEFINE OFF;
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (360,0,1,123,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于班组库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (350,0,2,123,to_timestamp('18-9月 -15 11.25.31.997000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'关于动态信息的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (354,0,1,119,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于班组库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (348,0,0,121,to_timestamp('18-9月 -15 02.13.44.232000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (355,0,3,121,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (353,0,3,122,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (356,0,1,121,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于班组库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (364,0,0,122,to_timestamp('18-9月 -15 03.47.07.708000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (365,0,3,121,to_timestamp('18-9月 -15 03.47.07.708000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (521,1,3,124,to_timestamp('13-11月-15 02.42.03.519000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'配件检修--主记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (418,1,3,140,to_timestamp('25-9月 -15 11.24.51.883000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库-记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (419,0,3,140,to_timestamp('25-9月 -15 11.24.51.883000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (345,0,2,122,to_timestamp('18-9月 -15 02.13.44.232000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于动态信息的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (343,0,2,119,to_timestamp('18-9月 -15 02.13.44.232000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于动态信息的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (344,0,2,121,to_timestamp('18-9月 -15 02.13.44.232000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于动态信息的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (346,0,3,119,to_timestamp('18-9月 -15 02.13.44.232000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (347,0,3,122,to_timestamp('18-9月 -15 02.13.44.232000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (349,0,1,119,to_timestamp('18-9月 -15 02.36.31.359000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于班组库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (358,0,0,123,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (359,0,1,123,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于班组库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (362,0,3,126,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于动态信息的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (400,0,3,136,to_timestamp('24-9月 -15 08.22.31.002000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (402,1,3,136,to_timestamp('24-9月 -15 08.22.31.002000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库-记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (412,1,3,138,to_timestamp('25-9月 -15 10.34.53.148000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库-记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (414,0,3,138,to_timestamp('25-9月 -15 10.34.53.148000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (495,1,2,145,to_timestamp('09-10月-15 02.57.01.731000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'委外检修记录主记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (351,0,1,119,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于班组库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (361,0,3,124,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于动态信息的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (357,0,1,119,to_timestamp('18-9月 -15 02.55.05.433000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于班组库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (363,0,3,121,to_timestamp('18-9月 -15 03.47.07.708000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (501,1,3,124,to_timestamp('09-11月-15 03.11.18.832000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'配件检修--主记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (437,1,3,146,to_timestamp('25-9月 -15 04.00.57.587000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库-记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (431,1,3,144,to_timestamp('25-9月 -15 11.44.22.108000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库-记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (432,0,3,144,to_timestamp('25-9月 -15 11.44.22.108000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (436,0,3,146,to_timestamp('25-9月 -15 04.00.57.587000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (352,0,0,121,to_timestamp('18-9月 -15 02.36.31.359000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (366,0,0,119,to_timestamp('18-9月 -15 04.49.40.192000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'关于主仓库和班组库的主要记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (433,1,3,145,to_timestamp('25-9月 -15 11.44.22.416000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库-记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (434,0,3,145,to_timestamp('25-9月 -15 11.44.22.416000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (425,0,3,142,to_timestamp('25-9月 -15 11.42.21.294000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (426,1,3,142,to_timestamp('25-9月 -15 11.42.21.294000000 上午','DD-MON-RR HH.MI.SS.FF AM'),'配件下车检修入库-记录');
Insert into TEST.PJ_S_D_INFO_RECORD (ID,RECEIVING_DELIVER_STATUS,STORE_UNIT_PROTEAM_STATUS,PJ_STORE_DYNAMIC_INFO_ID,RECORD_TIEM,REMARK) values (499,1,2,146,to_timestamp('10-10月-15 02.34.30.155000000 下午','DD-MON-RR HH.MI.SS.FF AM'),'委外检修记录主记录');
--------------------------------------------------------
--  DDL for Index SYS_C0012164
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012164" ON "TEST"."PJ_S_D_INFO_RECORD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PJ_S_D_INFO_RECORD
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD" ADD CONSTRAINT "PSDIR_CK_DELIVER_STATUS" CHECK (RECEIVING_DELIVER_STATUS in(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD" ADD CONSTRAINT "PSDIR_CK_PROTEAM_STATUS" CHECK (STORE_UNIT_PROTEAM_STATUS in(0,1,2,3)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_S_D_INFO_RECORD
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD" ADD CONSTRAINT "PSDIRPSDI_FOR" FOREIGN KEY ("PJ_STORE_DYNAMIC_INFO_ID")
	  REFERENCES "TEST"."PJ_STORE_DYNAMIC_INFO" ("ID") ENABLE;
