--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_STATIC_JC_TYPE_PJ_F_U
--------------------------------------------------------

  CREATE TABLE "TEST"."PJ_STATIC_JC_TYPE_PJ_F_U" 
   (	"ID" NUMBER, 
	"PJ_STATIC_ID" NUMBER, 
	"JC_TYPE_PJ_F_U" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TEST.PJ_STATIC_JC_TYPE_PJ_F_U
SET DEFINE OFF;
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (7,21,12);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (12,28,13);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (5,24,14);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (6,24,13);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (34,7,11);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (18,27,14);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (19,27,12);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (20,27,13);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (53,22,14);
Insert into TEST.PJ_STATIC_JC_TYPE_PJ_F_U (ID,PJ_STATIC_ID,JC_TYPE_PJ_F_U) values (54,22,13);
--------------------------------------------------------
--  DDL for Index SYS_C0012208
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012208" ON "TEST"."PJ_STATIC_JC_TYPE_PJ_F_U" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PJ_STATIC_JC_TYPE_PJ_F_U
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_STATIC_JC_TYPE_PJ_F_U" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_STATIC_JC_TYPE_PJ_F_U
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_STATIC_JC_TYPE_PJ_F_U" ADD FOREIGN KEY ("PJ_STATIC_ID")
	  REFERENCES "TEST"."PJ_STORE_STATIC_INFO" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_STATIC_JC_TYPE_PJ_F_U" ADD FOREIGN KEY ("JC_TYPE_PJ_F_U")
	  REFERENCES "TEST"."JC_TYPE_PJ_FIRST_UNIT" ("ID") ENABLE;
