--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_S_D_INFO_RECORD_PP
--------------------------------------------------------

  CREATE TABLE "TEST"."PJ_S_D_INFO_RECORD_PP" 
   (	"ID" NUMBER, 
	"PJ_S_D_INFO_RECORD_ID" NUMBER, 
	"PROTEAM_USERS_A_ID" NUMBER, 
	"PROTEAM_USERS_B_ID" NUMBER, 
	"REMARK" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_PP"."ID" IS '主键<序列自增>';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_PP"."PJ_S_D_INFO_RECORD_ID" IS '动态配件出入库记录ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_PP"."PROTEAM_USERS_A_ID" IS '班组人员AID，A是一个变量，代表A班组的一个人';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_PP"."PROTEAM_USERS_B_ID" IS '班组人员AID，B是一个变量，代表B班组的一个人';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_PP"."REMARK" IS '备注';
 
   COMMENT ON TABLE "TEST"."PJ_S_D_INFO_RECORD_PP"  IS '配件仓库动态信息记录表-子表，配件移库[班组仓库和班组仓库]';
REM INSERTING into TEST.PJ_S_D_INFO_RECORD_PP
SET DEFINE OFF;
Insert into TEST.PJ_S_D_INFO_RECORD_PP (ID,PJ_S_D_INFO_RECORD_ID,PROTEAM_USERS_A_ID,PROTEAM_USERS_B_ID,REMARK) values (9,354,null,null,'关于班组移至班组的子记录');
Insert into TEST.PJ_S_D_INFO_RECORD_PP (ID,PJ_S_D_INFO_RECORD_ID,PROTEAM_USERS_A_ID,PROTEAM_USERS_B_ID,REMARK) values (13,360,84,84,'关于班组移至班组的子记录');
Insert into TEST.PJ_S_D_INFO_RECORD_PP (ID,PJ_S_D_INFO_RECORD_ID,PROTEAM_USERS_A_ID,PROTEAM_USERS_B_ID,REMARK) values (10,356,null,null,'关于班组移至班组的子记录');
Insert into TEST.PJ_S_D_INFO_RECORD_PP (ID,PJ_S_D_INFO_RECORD_ID,PROTEAM_USERS_A_ID,PROTEAM_USERS_B_ID,REMARK) values (7,349,null,null,'关于班组移至班组的子记录');
Insert into TEST.PJ_S_D_INFO_RECORD_PP (ID,PJ_S_D_INFO_RECORD_ID,PROTEAM_USERS_A_ID,PROTEAM_USERS_B_ID,REMARK) values (12,359,null,null,'关于班组移至班组的子记录');
Insert into TEST.PJ_S_D_INFO_RECORD_PP (ID,PJ_S_D_INFO_RECORD_ID,PROTEAM_USERS_A_ID,PROTEAM_USERS_B_ID,REMARK) values (8,351,null,null,'关于班组移至班组的子记录');
Insert into TEST.PJ_S_D_INFO_RECORD_PP (ID,PJ_S_D_INFO_RECORD_ID,PROTEAM_USERS_A_ID,PROTEAM_USERS_B_ID,REMARK) values (11,357,null,null,'关于班组移至班组的子记录');
--------------------------------------------------------
--  DDL for Index SYS_C0012165
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012165" ON "TEST"."PJ_S_D_INFO_RECORD_PP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PJ_S_D_INFO_RECORD_PP
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD_PP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_S_D_INFO_RECORD_PP
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD_PP" ADD CONSTRAINT "PSDIRPPSDIRS_FOR" FOREIGN KEY ("PJ_S_D_INFO_RECORD_ID")
	  REFERENCES "TEST"."PJ_S_D_INFO_RECORD" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD_PP" ADD CONSTRAINT "PSDIRPUP_FOR_A" FOREIGN KEY ("PROTEAM_USERS_A_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD_PP" ADD CONSTRAINT "PSDIRPUP_FOR_B" FOREIGN KEY ("PROTEAM_USERS_B_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
