--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_STORE_DYNAMIC_INFO
--------------------------------------------------------

  CREATE TABLE "TEST"."PJ_STORE_DYNAMIC_INFO" 
   (	"ID" NUMBER, 
	"PJD_PARENT_ID" NUMBER, 
	"PJD_CODE" VARCHAR2(255 BYTE), 
	"STORE_POSITION_ID" NUMBER, 
	"PJD_STATUS" NUMBER DEFAULT 0, 
	"PJD_FACTORY" VARCHAR2(255 BYTE), 
	"PJD_OUT_FACTORY_DATE" TIMESTAMP (6), 
	"PJD_IN_PRICE" NUMBER(12,2), 
	"PY" VARCHAR2(255 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE), 
	"PJ_STORE_STATIC_INFO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."ID" IS '主键<序列增长>';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PJD_PARENT_ID" IS '配件父级ID';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PJD_CODE" IS '配件编码,按编码规则执行,唯一';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."STORE_POSITION_ID" IS '配件所在位置/仓库ID';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PJD_STATUS" IS '配件状态：0、新件合格；1、修竣合格；2、待修；3、报废；4、检修中,5、委外I检修；6、组装上车；默认0';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PJD_FACTORY" IS '配件生产厂家';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PJD_OUT_FACTORY_DATE" IS '配件出厂日期';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PJD_IN_PRICE" IS '配件进货价格';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PY" IS '拼音';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "TEST"."PJ_STORE_DYNAMIC_INFO"."PJ_STORE_STATIC_INFO_ID" IS '静态表ID';
 
   COMMENT ON TABLE "TEST"."PJ_STORE_DYNAMIC_INFO"  IS '配件仓库动态信息/库存(所在位置)表';
REM INSERTING into TEST.PJ_STORE_DYNAMIC_INFO
SET DEFINE OFF;
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (123,null,'CGLZ20150922001',29,1,'sda',to_timestamp('18-9月 -15 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),2,null,'sa',22);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (140,null,'CGLZ20150922015',null,2,'非必填',to_timestamp('05-5月 -15 10.20.10.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),10,null,null,7);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (119,null,'CGLZ20150922004',25,1,'sad',null,1,null,'sdasd',22);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (122,null,'CGLZ20150922002',29,1,'sadas',null,23,null,'ddd',22);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (121,null,'CGLZ20150922003',29,1,'dsa',to_timestamp('18-9月 -15 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),123,null,'asdas',22);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (126,null,'HCLZ201509020002',null,4,'sdfsa',to_timestamp('24-9月 -15 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),42334,null,'fdasfas',21);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (136,null,'HCLZ201509020014',null,4,'非必填',to_timestamp('05-5月 -15 10.20.10.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),10,null,null,21);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (138,null,'CGLZ2015092201522',null,4,'非必填',to_timestamp('05-5月 -15 10.20.10.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,24);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (124,null,'HCLZ201509020003',25,4,'kjk',to_timestamp('15-9月 -15 12.00.00.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),76,null,'uiyui',21);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (144,null,'CGLZ20150922019',null,2,'非必填',to_timestamp('05-5月 -15 10.20.10.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),10,null,null,21);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (146,null,'123333333',null,5,'非必填',to_timestamp('05-5月 -15 10.20.10.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,28);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (142,null,'CGLZ20150922017',null,2,'非必填',to_timestamp('05-5月 -15 10.20.10.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),10,null,null,7);
Insert into TEST.PJ_STORE_DYNAMIC_INFO (ID,PJD_PARENT_ID,PJD_CODE,STORE_POSITION_ID,PJD_STATUS,PJD_FACTORY,PJD_OUT_FACTORY_DATE,PJD_IN_PRICE,PY,REMARK,PJ_STORE_STATIC_INFO_ID) values (145,null,'CGLZ20150922020',null,5,'非必填',to_timestamp('05-5月 -15 10.20.10.000000000 上午','DD-MON-RR HH.MI.SS.FF AM'),10,null,null,21);
--------------------------------------------------------
--  DDL for Index UK_PJ_SD_INFO_PJD_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."UK_PJ_SD_INFO_PJD_CODE" ON "TEST"."PJ_STORE_DYNAMIC_INFO" ("PJD_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012192
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012192" ON "TEST"."PJ_STORE_DYNAMIC_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PJ_STORE_DYNAMIC_INFO
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_STORE_DYNAMIC_INFO" ADD CONSTRAINT "PSDI_CK_STATUS" CHECK (PJD_STATUS in(0,1,2,3,4,5,6)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_STORE_DYNAMIC_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."PJ_STORE_DYNAMIC_INFO" ADD CONSTRAINT "UK_PJ_SD_INFO_PJD_CODE" UNIQUE ("PJD_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_STORE_DYNAMIC_INFO
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_STORE_DYNAMIC_INFO" ADD CONSTRAINT "PSDIDSP_FOR" FOREIGN KEY ("STORE_POSITION_ID")
	  REFERENCES "TEST"."DICT_STORE_POSITION" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_STORE_DYNAMIC_INFO" ADD CONSTRAINT "PSDIPSDI_FOR" FOREIGN KEY ("PJD_PARENT_ID")
	  REFERENCES "TEST"."PJ_STORE_DYNAMIC_INFO" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_STORE_DYNAMIC_INFO" ADD FOREIGN KEY ("PJ_STORE_STATIC_INFO_ID")
	  REFERENCES "TEST"."PJ_STORE_STATIC_INFO" ("ID") ENABLE;
