--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_S_D_INFO_RECORD_SU
--------------------------------------------------------

  CREATE TABLE "TEST"."PJ_S_D_INFO_RECORD_SU" 
   (	"ID" NUMBER, 
	"PJ_S_D_INFO_RECORD_ID" NUMBER, 
	"CORRELATION_UNIT" VARCHAR2(255 BYTE), 
	"CORRELATION_NAME" VARCHAR2(255 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE), 
	"STORE_USERS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_SU"."ID" IS '主键<序列自增>';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_SU"."PJ_S_D_INFO_RECORD_ID" IS '动态配件出入库记录ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_SU"."CORRELATION_UNIT" IS '相关单位，一般只送货单位';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_SU"."CORRELATION_NAME" IS '相关单位人员，一般指送人人员';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_SU"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_INFO_RECORD_SU"."STORE_USERS_ID" IS '仓库人员ID<USERPRIVS>';
 
   COMMENT ON TABLE "TEST"."PJ_S_D_INFO_RECORD_SU"  IS '配件仓库动态信息记录表-子表，配件移库[主仓库和班组仓库]';
REM INSERTING into TEST.PJ_S_D_INFO_RECORD_SU
SET DEFINE OFF;
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (88,350,'sds','s','关于新建动态配件时，添加的关于配件仓库和相关单位的子记录',87);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (103,419,null,null,'配件下车检修入库-记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (85,343,'asdas','asd','关于新建动态配件时，添加的关于配件仓库和相关单位的子记录',87);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (86,344,'sd','sd','关于新建动态配件时，添加的关于配件仓库和相关单位的子记录',87);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (87,345,'sad','dd','关于新建动态配件时，添加的关于配件仓库和相关单位的子记录',87);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (90,362,'ds','sdfds','关于新建动态配件时，添加的关于配件仓库和相关单位的子记录',87);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (99,400,null,null,'配件下车检修入库-记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (101,414,null,null,'配件下车检修入库-记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (126,495,null,null,'委外检修子记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (89,361,'yukuy','ui','关于新建动态配件时，添加的关于配件仓库和相关单位的子记录',87);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (107,432,null,null,'配件下车检修入库-记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (109,436,null,null,'配件下车检修入库-记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (105,425,null,null,'配件下车检修入库-记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (108,434,null,null,'配件下车检修入库-记录',null);
Insert into TEST.PJ_S_D_INFO_RECORD_SU (ID,PJ_S_D_INFO_RECORD_ID,CORRELATION_UNIT,CORRELATION_NAME,REMARK,STORE_USERS_ID) values (127,499,null,null,'委外检修子记录',null);
--------------------------------------------------------
--  DDL for Index SYS_C0012160
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012160" ON "TEST"."PJ_S_D_INFO_RECORD_SU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PJ_S_D_INFO_RECORD_SU
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD_SU" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_S_D_INFO_RECORD_SU
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD_SU" ADD CONSTRAINT "PSDIRSPSDIR_FOR" FOREIGN KEY ("PJ_S_D_INFO_RECORD_ID")
	  REFERENCES "TEST"."PJ_S_D_INFO_RECORD" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_INFO_RECORD_SU" ADD CONSTRAINT "PSDIRS_FOR" FOREIGN KEY ("STORE_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
