--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_S_D_I_RECORD_FIX_CHECK
--------------------------------------------------------

  CREATE TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" 
   (	"ID" NUMBER, 
	"PJ_S_D_INFO_RECRD_FIX_ID" NUMBER, 
	"LEAD_USERS_ID" NUMBER, 
	"LEAD_CHECK" NUMBER, 
	"LEAD_CHECK_TIME" TIMESTAMP (6), 
	"COMMIT_LEAD_USERS_ID" NUMBER, 
	"COMMIT_LEAD_CHECK" NUMBER, 
	"COMMIT_LEAD_CHECK_TIME" TIMESTAMP (6), 
	"QC_USERS_ID" NUMBER, 
	"QC_CHECK" NUMBER, 
	"QC_CHECK_TIME" TIMESTAMP (6), 
	"ACCEPTANCE_USERS_ID" NUMBER, 
	"ACCEPTANCE_CHECK" NUMBER, 
	"ACCEPTANCE_CHECK_TIME" TIMESTAMP (6), 
	"TECHNICIAN_USERS_ID" NUMBER, 
	"TECHNICIAN_CHECK" NUMBER, 
	"TECHNICIAN_CHECK_TIME" TIMESTAMP (6), 
	"TWO_INSPECTION_USERS_ID" NUMBER, 
	"TWO_INSPECTION_CHECK" NUMBER, 
	"TWO_INSPECTION_CHECK_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."ID" IS '主键<序列自增>';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."PJ_S_D_INFO_RECRD_FIX_ID" IS '配件动态信息检修记录表ID，表明该条卡控是为那条配件检修记录进行卡控';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."LEAD_USERS_ID" IS '工长ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."LEAD_CHECK" IS '工长是否卡控（0、不卡控；1、卡控';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."LEAD_CHECK_TIME" IS '工长验收时间';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."COMMIT_LEAD_USERS_ID" IS '交车工长ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."COMMIT_LEAD_CHECK" IS '交车工长是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."COMMIT_LEAD_CHECK_TIME" IS '交车工长验收时间';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."QC_USERS_ID" IS '质检员ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."QC_CHECK" IS '质检员是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."QC_CHECK_TIME" IS '质检员验收时间';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."ACCEPTANCE_USERS_ID" IS '验收员ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."ACCEPTANCE_CHECK" IS '验收员是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."ACCEPTANCE_CHECK_TIME" IS '验收员验收时间';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."TECHNICIAN_USERS_ID" IS '技术员ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."TECHNICIAN_CHECK" IS '技术员是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."TECHNICIAN_CHECK_TIME" IS '技术员验收时间';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."TWO_INSPECTION_USERS_ID" IS '复探ID';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."TWO_INSPECTION_CHECK" IS '复探是否卡控（0、不卡控；1、卡控）';
 
   COMMENT ON COLUMN "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"."TWO_INSPECTION_CHECK_TIME" IS '复探验收时间';
 
   COMMENT ON TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK"  IS '配件动态信息检修记录，卡控信息';
REM INSERTING into TEST.PJ_S_D_I_RECORD_FIX_CHECK
SET DEFINE OFF;
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (202,202,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (203,203,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (204,204,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (205,205,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (206,206,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (201,201,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null,null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (181,181,88,1,to_timestamp('10-11月-15 03.19.43.464000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (182,182,88,1,to_timestamp('10-11月-15 03.19.43.464000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (183,183,88,1,to_timestamp('10-11月-15 03.19.43.464000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (184,184,88,1,to_timestamp('10-11月-15 03.19.43.464000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (185,185,88,1,to_timestamp('10-11月-15 03.53.21.889000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),null,1,null);
Insert into TEST.PJ_S_D_I_RECORD_FIX_CHECK (ID,PJ_S_D_INFO_RECRD_FIX_ID,LEAD_USERS_ID,LEAD_CHECK,LEAD_CHECK_TIME,COMMIT_LEAD_USERS_ID,COMMIT_LEAD_CHECK,COMMIT_LEAD_CHECK_TIME,QC_USERS_ID,QC_CHECK,QC_CHECK_TIME,ACCEPTANCE_USERS_ID,ACCEPTANCE_CHECK,ACCEPTANCE_CHECK_TIME,TECHNICIAN_USERS_ID,TECHNICIAN_CHECK,TECHNICIAN_CHECK_TIME,TWO_INSPECTION_USERS_ID,TWO_INSPECTION_CHECK,TWO_INSPECTION_CHECK_TIME) values (186,186,88,1,to_timestamp('10-11月-15 03.53.21.889000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 03.57.39.163000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),88,1,to_timestamp('10-11月-15 04.21.11.973000000 下午','DD-MON-RR HH.MI.SS.FF AM'),null,1,null);
--------------------------------------------------------
--  DDL for Index SYS_C0012175
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012175" ON "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PJ_S_D_I_RECORD_FIX_CHECK
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFC_CK_A_CHECK" CHECK (ACCEPTANCE_CHECK IN(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFC_CK_C_L_CHECK" CHECK (COMMIT_LEAD_CHECK IN(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFC_CK_L_CHECK" CHECK (LEAD_CHECK IN(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFC_CK_Q_CHECK" CHECK (QC_CHECK IN(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFC_CK_T_CHECK" CHECK (TECHNICIAN_CHECK IN(0,1)) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFC_CK_T_M_CHECK" CHECK ("TWO_INSPECTION_CHECK"=0 OR "TWO_INSPECTION_CHECK"=1) ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_S_D_I_RECORD_FIX_CHECK
--------------------------------------------------------

  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFCPSDIRF_FOR" FOREIGN KEY ("PJ_S_D_INFO_RECRD_FIX_ID")
	  REFERENCES "TEST"."PJ_S_D_INFO_RECORD_FIX" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFCUP_AUI_FOR" FOREIGN KEY ("ACCEPTANCE_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFCUP_CLUI_FOR" FOREIGN KEY ("COMMIT_LEAD_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFCUP_LUI_FOR" FOREIGN KEY ("LEAD_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFCUP_QUI_FOR" FOREIGN KEY ("QC_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFCUP_TMUI_FOR" FOREIGN KEY ("TWO_INSPECTION_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PJ_S_D_I_RECORD_FIX_CHECK" ADD CONSTRAINT "PSDIRFCUP_TUI_FOR" FOREIGN KEY ("TECHNICIAN_USERS_ID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
