--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROTEAM_PJ_STATIC
--------------------------------------------------------

  CREATE TABLE "TEST"."PROTEAM_PJ_STATIC" 
   (	"ID" NUMBER, 
	"PROTEAM_ID" NUMBER, 
	"PJ_STATIC_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TEST.PROTEAM_PJ_STATIC
SET DEFINE OFF;
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (7,37,21);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (8,35,21);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (11,37,28);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (6,35,24);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (28,37,7);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (29,36,7);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (15,36,27);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (34,37,22);
Insert into TEST.PROTEAM_PJ_STATIC (ID,PROTEAM_ID,PJ_STATIC_ID) values (35,35,22);
--------------------------------------------------------
--  DDL for Index SYS_C0012157
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012157" ON "TEST"."PROTEAM_PJ_STATIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROTEAM_PJ_STATIC
--------------------------------------------------------

  ALTER TABLE "TEST"."PROTEAM_PJ_STATIC" MODIFY ("PROTEAM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."PROTEAM_PJ_STATIC" MODIFY ("PJ_STATIC_ID" NOT NULL DISABLE);
 
  ALTER TABLE "TEST"."PROTEAM_PJ_STATIC" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROTEAM_PJ_STATIC
--------------------------------------------------------

  ALTER TABLE "TEST"."PROTEAM_PJ_STATIC" ADD FOREIGN KEY ("PROTEAM_ID")
	  REFERENCES "TEST"."DICT_PROTEAM" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."PROTEAM_PJ_STATIC" ADD FOREIGN KEY ("PJ_STATIC_ID")
	  REFERENCES "TEST"."PJ_STORE_STATIC_INFO" ("ID") ENABLE;
