--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ROLE_FUNCTION_PRIVS
--------------------------------------------------------

  CREATE TABLE "TEST"."ROLE_FUNCTION_PRIVS" 
   (	"ID" NUMBER, 
	"ROLEID" NUMBER, 
	"FUNCTIONID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."ROLE_FUNCTION_PRIVS"."ID" IS '主键';
 
   COMMENT ON COLUMN "TEST"."ROLE_FUNCTION_PRIVS"."ROLEID" IS '角色ID（外键ROLE_PRIVS表ID）';
 
   COMMENT ON COLUMN "TEST"."ROLE_FUNCTION_PRIVS"."FUNCTIONID" IS '功能ID（外键FUNCTION_PRIVS表ID）';
 
   COMMENT ON TABLE "TEST"."ROLE_FUNCTION_PRIVS"  IS '角色功能表';
REM INSERTING into TEST.ROLE_FUNCTION_PRIVS
SET DEFINE OFF;
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (18,37,51);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (19,37,50);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (184,59,100);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (93,39,97);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (95,39,34);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (96,39,33);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (180,59,93);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (92,39,98);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (181,59,92);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (182,59,1102);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (183,59,101);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (185,59,83);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (186,59,82);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (187,59,81);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (188,59,80);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (119,42,47);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (120,42,46);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (121,42,45);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (122,42,44);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (123,42,43);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (124,42,42);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (125,42,41);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (126,42,40);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (127,42,39);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (128,42,38);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (129,42,37);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (130,42,36);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (131,42,35);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (132,42,34);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (133,42,33);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (136,38,79);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (137,38,78);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (138,38,77);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (139,38,76);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (94,39,96);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (140,38,75);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (91,39,99);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (141,38,74);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (142,38,73);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (143,38,72);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (144,38,71);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (145,38,70);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (146,38,69);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (147,38,105);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (148,38,104);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (149,38,68);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (134,38,81);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (135,38,80);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (150,38,67);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (151,38,66);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (152,38,65);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (153,38,64);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (154,38,63);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (155,38,62);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (156,38,61);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (157,38,60);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (158,38,59);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (159,38,58);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (160,38,57);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (161,38,37);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (162,38,36);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (163,38,35);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (164,38,34);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (165,45,47);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (166,45,46);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (167,45,45);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (168,45,44);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (169,45,43);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (170,45,42);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (171,45,41);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (172,45,40);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (173,45,39);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (174,45,38);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (175,45,37);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (176,45,36);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (177,45,35);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (178,45,34);
Insert into TEST.ROLE_FUNCTION_PRIVS (ID,ROLEID,FUNCTIONID) values (179,45,33);
--------------------------------------------------------
--  DDL for Index SYS_C0012186
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012186" ON "TEST"."ROLE_FUNCTION_PRIVS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ROLE_FUNCTION_PRIVS
--------------------------------------------------------

  ALTER TABLE "TEST"."ROLE_FUNCTION_PRIVS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLE_FUNCTION_PRIVS
--------------------------------------------------------

  ALTER TABLE "TEST"."ROLE_FUNCTION_PRIVS" ADD CONSTRAINT "FK_FUNCTION_ID" FOREIGN KEY ("FUNCTIONID")
	  REFERENCES "TEST"."FUNCTION_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."ROLE_FUNCTION_PRIVS" ADD CONSTRAINT "FK_ROLE_ID" FOREIGN KEY ("ROLEID")
	  REFERENCES "TEST"."ROLE_PRIVS" ("ID") ENABLE;
