--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS_PRIVS
--------------------------------------------------------

  CREATE TABLE "TEST"."USERS_PRIVS" 
   (	"ID" NUMBER, 
	"AREAID" VARCHAR2(255 BYTE), 
	"STATUS" NUMBER, 
	"DEPARTID" NUMBER, 
	"PROTEAMID" NUMBER, 
	"USER_NAME" VARCHAR2(255 BYTE), 
	"JOB_NUM" VARCHAR2(255 BYTE), 
	"CARD_NUM" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"GENDER" NUMBER, 
	"PY" VARCHAR2(255 BYTE), 
	"REMARK" VARCHAR2(1000 BYTE), 
	"DEPART_PROTEAM_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."ID" IS '主键（序列增长）';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."AREAID" IS '地区ID（外键关联DICT_AREA表ID）';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."STATUS" IS '激活：0、激活；1、未激活';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."DEPARTID" IS '部门ID（外键关联DICT_DEPAT表ID）';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."PROTEAMID" IS '班组ID（外键关联DICT_PROTEAM表ID）';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."USER_NAME" IS '用户姓名';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."JOB_NUM" IS '工号（登录帐号）';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."CARD_NUM" IS '卡号';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."PASSWORD" IS '登录密码';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."GENDER" IS '性别：0、男；1、女';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."PY" IS '拼音';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."REMARK" IS '备注';
 
   COMMENT ON COLUMN "TEST"."USERS_PRIVS"."DEPART_PROTEAM_STATUS" IS '人员班组部门属性判别字段：0、属于部门（DEPARTID有值）；1、属于班组（PROTEAMID有值）；2、即属于部门又属于班组（DEPARTID、PROTEAMID有值）。';
 
   COMMENT ON TABLE "TEST"."USERS_PRIVS"  IS '用户表';
REM INSERTING into TEST.USERS_PRIVS
SET DEFINE OFF;
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (84,'20144',1,null,36,'张伟','dvda','sdfsdf','dvda',0,'zw',null,1);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (88,'20144',1,null,36,'管理员','admin','admin','admin',0,'admin',null,1);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (87,'20144',1,38,null,'少川枫','sdf','sdfds','sdfsdf',0,'scf','dsfds',0);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (56,'20144',1,37,null,'周一套','thh','thh','thh',0,'zyt',null,0);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (1,'2018',1,null,36,'成天','123456','123456','123456',0,'ct','dsfsfdfd',1);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (54,'20144',1,null,36,'廖雪冰','oo','oo','oo',0,'lxb',null,1);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (57,'20144',1,36,null,'航海风','foo','foo','foo',0,'hhf','foo',0);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (58,'20144',1,36,null,'蔡文','fii','fii','fii',0,'cw','fii',0);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (59,'20144',1,38,null,'顺无能','sii','sii','sii',0,'swn','sii',0);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (74,'20144',1,null,36,'猪无能','dfssd','sads','dfssd',0,'zwn','awesd',1);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (76,'20144',1,null,36,'沙悟净','fdgdf','fsdf','fdgdf',0,'swj','dfsdfs',1);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (67,'20144',1,null,36,'汤桑张','ohot','ohot','ohot',0,'tsz',null,1);
Insert into TEST.USERS_PRIVS (ID,AREAID,STATUS,DEPARTID,PROTEAMID,USER_NAME,JOB_NUM,CARD_NUM,PASSWORD,GENDER,PY,REMARK,DEPART_PROTEAM_STATUS) values (70,'20144',1,null,36,'唐三藏','ohofi','ohofi','ohofi',0,'tsz',null,1);
--------------------------------------------------------
--  DDL for Index SYS_C0012210
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012210" ON "TEST"."USERS_PRIVS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS_PRIVS
--------------------------------------------------------

  ALTER TABLE "TEST"."USERS_PRIVS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS_PRIVS
--------------------------------------------------------

  ALTER TABLE "TEST"."USERS_PRIVS" ADD CONSTRAINT "FK_AREA_ID" FOREIGN KEY ("AREAID")
	  REFERENCES "TEST"."DICT_AREA" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."USERS_PRIVS" ADD CONSTRAINT "FK_DEPAT_ID" FOREIGN KEY ("DEPARTID")
	  REFERENCES "TEST"."DICT_DEPART" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."USERS_PRIVS" ADD CONSTRAINT "FK_PROTEAM_ID" FOREIGN KEY ("PROTEAMID")
	  REFERENCES "TEST"."DICT_PROTEAM" ("ID") ENABLE;
