--------------------------------------------------------
--  文件已创建 - 星期二-二月-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS_ROLE_PRIVS
--------------------------------------------------------

  CREATE TABLE "TEST"."USERS_ROLE_PRIVS" 
   (	"ID" NUMBER, 
	"USERSID" NUMBER, 
	"ROLEID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TEST.USERS_ROLE_PRIVS
SET DEFINE OFF;
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (86,54,43);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (87,54,42);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (76,null,45);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (77,null,38);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (78,null,40);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (79,null,43);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (53,70,43);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (96,87,54);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (97,87,42);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (9,84,40);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (10,84,55);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (11,84,54);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (12,84,37);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (13,67,42);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (27,56,42);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (28,57,43);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (29,58,38);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (30,59,42);
Insert into TEST.USERS_ROLE_PRIVS (ID,USERSID,ROLEID) values (41,70,59);
--------------------------------------------------------
--  DDL for Index SYS_C0012167
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C0012167" ON "TEST"."USERS_ROLE_PRIVS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS_ROLE_PRIVS
--------------------------------------------------------

  ALTER TABLE "TEST"."USERS_ROLE_PRIVS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS_ROLE_PRIVS
--------------------------------------------------------

  ALTER TABLE "TEST"."USERS_ROLE_PRIVS" ADD FOREIGN KEY ("USERSID")
	  REFERENCES "TEST"."USERS_PRIVS" ("ID") ENABLE;
 
  ALTER TABLE "TEST"."USERS_ROLE_PRIVS" ADD FOREIGN KEY ("ROLEID")
	  REFERENCES "TEST"."ROLE_PRIVS" ("ID") ENABLE;
